### ISSUE TITLE
Create a user DAO

### ISSUE THREAD

**Issue by camilosampedro** [camilosampedro/Aton#10]
Create a UserDAO to perform all User operations against the database.

It must include a interface and implementation with:
- Create method.
- Update method.
- Get method.
- Delete method.

It can easily be done based on other DAOs.

**Comment by ubaldop** [comment]
It seems already created.

See [here](https://github.com/camilosampedro/Aton/blob/master/app/dao/UserDAO.scala) for trait and see [here](https://github.com/camilosampedro/Aton/blob/master/app/dao/impl/UserDAOImpl.scala) for implementation.

**Comment by camilosampedro** [comment]
You are right, @P3trur0. Thank you!
