### ISSUE TITLE
Add a room button to block a certain user from that room

### ISSUE THREAD

**Issue by camilosampedro** [camilosampedro/Aton#14]
Add a _button_ on `views.roomPanel.scala.html` that open a modal window to enter the user that will be blocked and two Confirm-Cancel buttons.
- Remember that these buttons should be integrated with the messages API (`@messages("resource")`, on which `resource` is located on `/conf/messages.*`).

**Comment by minrwhite** [comment]
Can I take this one?

**Comment by camilosampedro** [comment]
Yes, please.

Beforehand thank you very much! 😄

**Comment by minrwhite** [comment]
Great! I probably will start work on this tomorrow morning - ~10am UK time

**Comment by camilosampedro** [comment]
Take your time! It is not something urgent. 😅
