### ISSUE TITLE
Translate to German

### ISSUE THREAD

**Issue by camilosampedro** [camilosampedro/Aton#22]
If someone there knows German, it would be **very** nice and useful to translate some Aton Strings on [Aton Transifex project](https://www.transifex.com/universidad-de-antioquia/aton-computer-laboratory-administrator).

**Comment by literalplus** [comment]
How would that work with the Hacktoberfest shirt-for-pr thing? Would one translate the strings in Transifex, copy them into a file (I found [messages.en](https://github.com/camilosampedro/Aton/blob/5ff48367066046c42fac24d5728ef23e2674cf7c/conf/messages.en)) and PR that?

**Comment by camilosampedro** [comment]
Hi, thank you for your interest.

You can translate the Strings on Transifex, download the result file (`messages.your_language`), add it into `conf/` folder and pull request that.

You can translate as much as you want and can.

Since the project is very new, you would be the first translator. If you have any advice it would be very helpful to let me know.

Have a good day.

**Comment by literalplus** [comment]
I submitted a join request to the team, which you apparently have to accept.

**Comment by literalplus** [comment]
On the login page, it seems like there are not translations for ["Password"](https://github.com/camilosampedro/Aton/blob/2d2ae58dbc12a071e79381a064e2f91315091ba1/app/views/login.scala.html#L30) and ["Login"](https://github.com/camilosampedro/Aton/blob/2d2ae58dbc12a071e79381a064e2f91315091ba1/app/views/login.scala.html#L34).

What's the process for that? Do I just submit a PR?

**Comment by camilosampedro** [comment]
That is a really good point. From my Spanish/English perspective I did not noticed the password and login. 

I can add a new `password` and `login` entry to the messages source and notify you when they are added. Or you can tell me if you want to do it.

By the way, feel free to submit a pull request when you want to do so. I will always review them. :pencil2:

**Comment by literalplus** [comment]
I noticed the suggestions page, but I don't get exactly what it does. Currently, any unauthenticated user can submit suggestions. Is this the place for students to go if they need something installed (requests), or is this actually for admins giving suggestions to the people who use the rooms? The help text in Spanish didn't help me much.

My current version of the translation assumes the first one, using the literal translation of `suggestion`.

**Comment by camilosampedro** [comment]
You are right with the first, suggestion page is the place where students can go and make requests or tell the admins if there is something bad with the room.

I will take into account this into making it more understandable.

Thank you very much.
