### ISSUE TITLE
Translate to Italian

### ISSUE THREAD

**Issue by camilosampedro** [camilosampedro/Aton#23]
If someone there knows Italian, it would be **very** nice and useful to translate some Aton Strings on [Aton Transifex project](https://www.transifex.com/universidad-de-antioquia/aton-computer-laboratory-administrator).

**Comment by camilosampedro** [comment]
You can add the `messages.it` to `conf/` folder

**Comment by ubaldop** [comment]
Was my pull request ok? If so, this could be closed :smile:

**Comment by camilosampedro** [comment]
Yeah, thank you @P3trur0!

I forgot to close it, sorry. 🙇
