### ISSUE TITLE
Translate to Portuguese

### ISSUE THREAD

**Issue by camilosampedro** [camilosampedro/Aton#25]
If someone there knows Portuguese, it would be **very** nice and useful to translate some Aton Strings on [Aton Transifex project](https://www.transifex.com/universidad-de-antioquia/aton-computer-laboratory-administrator).

**Comment by camilosampedro** [comment]
You can add the `messages.pt` to `conf/` folder

**Comment by marcobarbosa16** [comment]
Translate to Portuguese (Brazil)?

**Comment by camilosampedro** [comment]
Hi, thanks for your interest.

The idea is to have a general Portuguese translation, that any who knows Portuguese can understand. But I think it is not a big deal if you add Brazilian Portuguese translations, it is a good start point.

Thank you, by the way! 👍

**Comment by vinidf** [comment]
Hey, i'm interested and able to do this

I'll give a look at the project and try to help

**Comment by camilosampedro** [comment]
Thank you, @viniciusdfx, it would help the project a lot.
