### ISSUE TITLE
Translate to French

### ISSUE THREAD

**Issue by camilosampedro** [camilosampedro/Aton#26]
If someone there knows French, it would be **very** nice and useful to translate some Aton Strings on [Aton Transifex project](https://www.transifex.com/universidad-de-antioquia/aton-computer-laboratory-administrator).

**Comment by camilosampedro** [comment]
You can add the result `messages.fr` file to `conf/` folder

**Comment by rafajaques** [comment]
May I take this one?

**Comment by camilosampedro** [comment]
Ofcourse! 😄 

Remember, on Transifex you can configure it to translate from English instead of Spanish.

Thank you.

**Comment by farhatnader** [comment]
Currently translating some of the strings. Hope to have most of it done by end of week. What is the messages.fr file? Is it something that will be available after all strings translated?

**Comment by camilosampedro** [comment]
Hi, @rafajaques.

Thank you for being interested and contributing on Aton.

When you translate from Transifex, you can download the result, rename it to `messages.fr`, place it into `conf` folder (Or create it from GitHub) and create a pull request.

Just with that done, it will be added to Aton's code and the user can see the application in French when running.
