### ISSUE TITLE
Create a unit test for a controller recognized by sbt or activator or fix the existing one 

### ISSUE THREAD

**Issue by camilosampedro** [camilosampedro/Aton#33]
The existing tests under `test` folder are not being recognized by `sbt` or `activator`. The idea of this issue is to create a single unit test that can be recognized and create the other unit tests based on that working unit test.

Unit tests are required for building a stable and proven application.

Thank you!

**Comment by camilosampedro** [comment]
@P3trur0, your pull request helped a lot. I just found that another error was using `@Inject`, [this question](http://stackoverflow.com/questions/34159857/specs2-how-to-test-a-class-with-more-than-one-injected-dependency) has the answer to it. 

I fixed the existing test, but I won't push it until it actually tests.

**Comment by ubaldop** [comment]
@camilosampedro glad to hear that! Keep going then!

**Comment by camilosampedro** [comment]
I reopen this issue because [`ComputerControllerSpec`](https://github.com/camilosampedro/Aton/blob/tests-creation/test/controllers/admin/ComputerControllerSpec.scala) (The first test) could not be executed. The problem relies on the `executionContext` injection. It throws the following exception:

``` scala
[info] - should add a new computer *** FAILED ***
[info]   java.lang.RuntimeException: There is no started application
[info]   at scala.sys.package$.error(package.scala:27)
[info]   at play.api.Play$$anonfun$current$1.apply(Play.scala:86)
[info]   at play.api.Play$$anonfun$current$1.apply(Play.scala:86)
[info]   at scala.Option.getOrElse(Option.scala:121)
[info]   at play.api.Play$.current(Play.scala:86)
[info]   at jp.t2v.lab.play2.auth.CacheIdContainer.removeByUserId(CacheIdContainer.scala:31)
[info]   at jp.t2v.lab.play2.auth.CacheIdContainer.startNewSession(CacheIdContainer.scala:17)
[info]   at jp.t2v.lab.play2.auth.AsyncIdContainer$$anon$1.startNewSession(AsyncIdContainer.scala:20)
[info]   at jp.t2v.lab.play2.auth.test.Helpers$AuthFakeRequest$$anonfun$withLoggedIn$1.apply(Helpers.scala:16)
[info]   ...
```

I will keep trying!

**Comment by ubaldop** [comment]
I've just submitted a pull request where the Play specs can run properly.

**Comment by ubaldop** [comment]
So also this can be closed, right? :smile:

**Comment by camilosampedro** [comment]
Yeah! hahaha 😄 

Closed
