### ISSUE TITLE
Create unit test for LaboratoryController (LaboratoryControllerSpec)

### ISSUE THREAD

**Issue by camilosampedro** [camilosampedro/Aton#38]
Create a unit test for `controllers.LaboratoryController` controller. It might be pretty similar to [`ComputerControllerSpec`](https://github.com/camilosampedro/Aton/blob/master/test/controllers/admin/ComputerControllerSpec.scala):
- You would need to mock the dependencies of LaboratoryController (Add a return value to the needed methods without executing anything, they are not intended to be tested here).
- Check the return HTTP code of the methods (Firstly as you would expect them to be).

Don't worry if you don't know something about the functionality of this class, it will be a pleasure to me to answer your questions.

**Comment by ubaldop** [comment]
@camilosampedro if you please I can go with this.

**Comment by ubaldop** [comment]
Cool! Did you consider React also?

Il ven 21 ott 2016, 20:57 Camilo A. Sampedro Restrepo <
notifications@github.com> ha scritto:

**Comment by camilosampedro** [comment]
No, I haven't checked it out. I also need to study Angular2 from the beginning, so which do you think is easier and better (For simple tasks)? Angular2 or React?

**Comment by ubaldop** [comment]
I have no experience with Angular 2, but React is really interesting and
I'd suggest to give it a try!

Il mar 25 ott 2016, 22:49 Camilo A. Sampedro Restrepo <
notifications@github.com> ha scritto:

**Comment by camilosampedro** [comment]
The only needed thing is to not load the whole page, but update it when the server sends information. I will look for it, thank you as always, @P3trur0 !

**Comment by ubaldop** [comment]
@camilosampedro PR pushed here!
