### ISSUE TITLE
Create a docker environment for TravisCI

### ISSUE THREAD

**Issue by camilosampedro** [camilosampedro/Aton#45]
Add a docker configuration inside [`.travis.yml`](https://github.com/camilosampedro/Aton/blob/master/.travis.yml) file.

The requirements are:
 - It is required to have a MySQL execution.
 - It is required that the MySQL database have executed [`create.sql`](https://github.com/camilosampedro/Aton/blob/master/conf/default/create.sql) before test execution.

Thank you very much beforehand! 😄 

## Referencies:
[Travis CI documentation](https://docs.travis-ci.com/user/docker/)

**Comment by minrwhite** [comment]
I'd like to take this, please!
