### ISSUE TITLE
Passwords are not encrypted in the database

### ISSUE THREAD

**Issue by camilosampedro** [camilosampedro/Aton#6]
Users' passwords are not encrypted in the database and might be a problem if someone gets into it.

To achieve this it is needed to change the column type in `/conf/default/create.sql`and also change the login service to encrypt the user's input to match the one stored in the database.

**Comment by akilegaspi** [comment]
I would say that just set your data type to varchar and let the application do the encryption

**Comment by shiv4nsh** [comment]
@camilosampedro : Assign this task to me ! please let me know what needs to be done here !

**Comment by camilosampedro** [comment]
I think that @akilegaspi is right about this. It might be better to add the encryption before storing it on the database. @shiv4nsh, you are always welcome to contribute to Aton. For this issue it would be required to look for a good method to encrypt Strings on Scala (Preferably to take advantage of Scala's features, but Java could also help in case that Java does it better).

It is needed then:
1. Find a good method to encrypt Strings. (Find a good one)
2. Add the encryption step on the [`UserService.add`](https://github.com/camilosampedro/Aton/blob/master/app/services/impl/UserServiceImpl.scala#L16) method (You can use the passed user, create another with the password encrypted and then call the DAO `add` method.
3. Find the way to check user's password (String) against the previously encrypted String.
4. Add that comparison strategy to the [`UserService.checkAndGet`](https://github.com/camilosampedro/Aton/blob/master/app/services/impl/UserServiceImpl.scala#L20).
5. Create a pull request with the changes!

Thank you, @shiv4nsh.

If something is not clear (English is not my native language :sweat_smile:), you can ask me anytime.

**Comment by akilegaspi** [comment]
@camilosampedro You can assign this task to me, I'm actually doing it right now.

**Comment by camilosampedro** [comment]
Oh! I'm sorry, I got confused. Did @shiv4nsh do something on this task?

If @akilegaspi has already started and have more done I think is fair for him to finish it.

@akilegaspi, @shiv4nsh I'm sorry for the confusion 😅

**Comment by 4ndrej** [comment]
sorry guys but you should salt and hash passwords, not encrypt them.

**Comment by camilosampedro** [comment]
@4ndrej You are right, those are different things at the end. It is needed to salt and hash the passwords but not to encrypt them :smile:
